name = "traivel"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "traivel.automasi.my", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "traivel-db"
database_id = "local"
